version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: tesseract-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: tesseract
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tesseract-network

  # Next.js Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tesseract-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/tesseract
      - NEXTAUTH_SECRET=your-secret-key-here
      - NEXTAUTH_URL=http://localhost:3000
      - RESEND_API_KEY=re_placeholder_key_for_build
    depends_on:
      - postgres
    networks:
      - tesseract-network

  # Development version (optional)
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: tesseract-app-dev
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/tesseract
      - NEXTAUTH_SECRET=your-secret-key-here
      - NEXTAUTH_URL=http://localhost:3001
      - RESEND_API_KEY=re_placeholder_key_for_build
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - postgres
    networks:
      - tesseract-network
    profiles:
      - dev

volumes:
  postgres_data:

networks:
  tesseract-network:
    driver: bridge
